### ISSUE TITLE
Support clean url with no ".html" suffixes

### ISSUE THREAD

**Issue by curvature** [tweedegolf/memory-serve#11]
Thanks for creating this library and I'm using it to serve my static web site. The assets are simply a bunch of HTML, CSS, JS files,  however I'm exposing the so-called "clean urls" for the end user so that instead of "example.com/pricing.html", the user will visit and see "example.com/pricing" only for the file "pricing.html". The `add_alias` method partially solves this but results in serving identical content under two sets of urls which hurts SEO.

Can we add a configuration flag specifically for this and if enabled strip the .html extension in the path passed to the `Router::route` call. This flag only affects HTML files since urls for other types are considered invisible to users.

I'm happy to prepare a PR for this if my proposal sounds OK to you.

**Comment by marlonbaeten** [comment]
That sounds reasonable. I'm happy to accept a PR for this. Maybe you can add an option to https://github.com/tweedegolf/memory-serve/blob/59bdbb6363ccb103385f0f0c65b63ddfdbc79940/memory-serve/src/lib.rs#L23 that will strip the `.html` extension from the route.
