### ISSUE TITLE
Add a macro to serve files from OUT_DIR

### ISSUE THREAD

**Issue by BeneSim** [tweedegolf/memory-serve#3]
Hey,

I really like this crate but I'm facing a problem: I have some static files that get minified and packed using vite / rollup which itself gets called in a `build.rs` buildscript. One useful environment variable in such a build.rs script is `OUT_DIR` where I can store the build artifacts of npm build.

I want to include those build artifacts with memory_serve. However, you're just turning the input `TokenStream` in your proc Macro into a String so macros like `env!("OUT_DIR")`  won't get resolved. In fact, as far as I know resolving `TokenStream`s is unstable at the moment.

Maybe we can add another macro `load_assets_from_out_dir!` or something similar. I'm going to preare a PR for that that you might consider.

**Comment by marlonbaeten** [comment]
Thank you @BeneSim, and sorry for my late response.

That seems reasonable, but I would prefer not introducing a new macro. Would it be an option for you if I added a `MEMORY_SERVE_ROOT` environment variable that would have priority over `CARGO_MANIFEST_DIR` when resolving a relative path? See #5

**Comment by marlonbaeten** [comment]
I have released version 0.4.4 - hopefully this solves your issue. If not - please reopen this issue.
