### ISSUE TITLE
Why not compress gzip with best-level compression?

### ISSUE THREAD

**Issue by droundy** [tweedegolf/memory-serve#7]
Just glancing through your code and it seems like you may as well use best compression rather than default, since you're only going to compress each file once and then store in memory for a long time.

**Comment by marlonbaeten** [comment]
My understanding was that level 6 is somewhat of a sweet-spot for gzip compression - and best compression makes compile times even longer. But you make a fair point. We can trade of some compilation speed for runtime performance.

**Comment by marlonbaeten** [comment]
Published in v0.4.5
